export const ONBOARDING_SCENE_IDS = [
  "account",
  "account-error",
  "additional",
  "api-error",
  "api-key",
  "business",
  "business-error",
  "businesses",
  "connect",
  "connected",
  "connection-error",
  "credits-cancelled",
  "credits-checkout",
  "credits-delayed",
  "credits-failed",
  "credits-pending",
  "credits-price-error",
  "credits-success",
  "credits-uncertain",
  "email-sent",
  "forgot",
  "funding",
  "history",
  "history-review",
  "invite",
  "new-password",
  "openrouter-connected",
  "openrouter-error",
  "openrouter-limit",
  "openrouter-unlinked",
  "reset-done",
  "reset-expired",
  "signin",
  "subscription-api-auth",
  "subscription-error",
  "subscription-exhausted",
  "subscription-missing",
  "subscription-models-error",
  "subscription-scan",
  "subscription-stale",
  "subscription-usage-unknown",
  "testing",
  "workspace",
] as const;

export type OnboardingSceneId = (typeof ONBOARDING_SCENE_IDS)[number];

export function onboardingSceneStage(scene: OnboardingSceneId): 0 | 1 | 2 {
  if (["business", "business-error", "additional"].includes(scene)) return 1;
  if (
    [
      "connect",
      "testing",
      "connected",
      "connection-error",
      "funding",
      "api-error",
      "api-key",
      "credits-cancelled",
      "credits-checkout",
      "credits-delayed",
      "credits-failed",
      "credits-pending",
      "credits-price-error",
      "credits-success",
      "credits-uncertain",
      "openrouter-connected",
      "openrouter-error",
      "openrouter-limit",
      "openrouter-unlinked",
      "subscription-api-auth",
      "subscription-error",
      "subscription-exhausted",
      "subscription-missing",
      "subscription-models-error",
      "subscription-scan",
      "subscription-stale",
      "subscription-usage-unknown",
    ].includes(scene)
  ) {
    return 2;
  }
  return 0;
}
