import { index, rootRoute, route } from "@tanstack/virtual-file-routes";

export const routes = rootRoute("root.tsx", [
  index("index.tsx"),
  route("/agents", "agents.tsx"),
  route("/supervision", "supervision.tsx"),
  route("/power", "power.tsx"),
  route("/today", "today.tsx"),
  route("/asks/$channelId/$askId", "asks.$channelId.$askId.tsx"),
  route("/permission/$", "permission.$.tsx"),
  route("/asks/new", "asks.new.tsx"),
  route("/today/updates", "today.updates.tsx"),
  route("/today/reviews-empty", "today.reviews-empty.tsx"),
  route("/navigation/history", "navigation.history.tsx"),
  route("/navigation/start", "navigation.start.tsx"),
  route("/pulse", "pulse.tsx"),
  route("/reminders", "reminders.tsx"),
  route("/settings", "settings.tsx"),
  route("/clients", "clients.tsx"),
  route("/clients/$clientId", "clients.$clientId.tsx"),
  route("/$workSurface", "work.tsx"),
  route("/work/$workId", "work.$workId.tsx"),
  route("/work/$screen/$resourceId", "work.$screen.$resourceId.tsx"),
  route("/workflows", "workflows.tsx"),
  route("/workflows/$workflowId", "workflows.$workflowId.tsx"),
  route("/projects", "projects.tsx"),
  route("/projects/$projectId", "projects.$projectId.tsx"),
  route("/team", "team.tsx"),
  route("/team/org", "team.org.tsx"),
  route("/team/detail/$memberPubkey", "team.detail.$memberPubkey.tsx"),
  route("/team/edit/$memberPubkey", "team.edit.$memberPubkey.tsx"),
  route("/team/pause/$memberPubkey", "team.pause.$memberPubkey.tsx"),
  route("/team/archive/$memberPubkey", "team.archive.$memberPubkey.tsx"),
  route("/goals", "goals.tsx"),
  route("/goals/link/$goalId", "goals.link.$goalId.tsx"),
  route("/goals/reference", "goals.reference.tsx"),
  route("/goals/$goalId", "goals.$goalId.tsx"),
  route("/goals/$goalId/edit", "goals.$goalId.edit.tsx"),
  route("/goals/$goalId/progress", "goals.$goalId.progress.tsx"),
  route("/goals/$goalId/archive", "goals.$goalId.archive.tsx"),
  route("/goals/$goalId/delete", "goals.$goalId.delete.tsx"),
  route("/goals/$goalId/subgoal", "goals.$goalId.subgoal.tsx"),
  route("/goals/$goalId/share", "goals.$goalId.share.tsx"),
  route("/discovery", "discovery.tsx"),
  route("/campaign", "campaign.tsx"),
  route("/leads", "leads.tsx"),
  route("/pipeline", "pipeline.tsx"),
  route("/money", "money.tsx"),
  route("/money/revenue", "money.revenue.tsx"),
  route("/money/revenue/$invoiceId", "money.revenue.$invoiceId.tsx"),
  route("/money/invoices", "money.invoices.tsx"),
  route("/money/invoice/$invoiceId", "money.invoice.$invoiceId.tsx"),
  route("/money/tax/$state", "money.tax.$state.tsx"),
  route("/money/costs/$state", "money.costs.$state.tsx"),
  route("/money/profitability/$state", "money.profitability.$state.tsx"),
  route("/money/adjustments", "money.adjustments.tsx"),
  route("/money/follow-ups", "money.follow-ups.tsx"),
  route("/sales/proposals", "sales.proposals.tsx"),
  route("/sales/service", "sales.service.tsx"),
  route("/sales/lead/form-field", "sales.lead.form-field.tsx"),
  route("/sales/lead/$prospectId", "sales.lead.$prospectId.tsx"),
  route("/sales/proposal/proposal-form", "sales.proposal.proposal-form.tsx"),
  route("/sales/proposal/$proposalId", "sales.proposal.$proposalId.tsx"),
  route("/factory", "factory.tsx"),
  route("/factory/projects", "factory.projects.tsx"),
  route("/factory/plans", "factory.plans.tsx"),
  route("/factory/plan/$planId", "factory.plan.$planId.tsx"),
  route("/factory/project/$projectId", "factory.project.$projectId.tsx"),
  route("/factory/review/$runId", "factory.review.$runId.tsx"),
  route("/factory/sessions", "factory.sessions.tsx"),
  route("/factory/states", "factory.states.tsx"),
  route("/messages/new", "messages.new.tsx"),
  route("/channels/pins/$channelId", "channels.pins.$channelId.tsx"),
  route("/channels/$channelId", "channels.$channelId.tsx"),
  route(
    "/channels/$channelId/posts/$postId",
    "channels.$channelId.posts.$postId.tsx",
  ),
]);
