import { index, rootRoute, route } from "@tanstack/virtual-file-routes";

export const routes = rootRoute("root.tsx", [
  index("index.tsx"),
  route("/agents", "agents.tsx"),
  route("/supervision", "supervision.tsx"),
  route("/power", "power.tsx"),
  route("/today", "today.tsx"),
  route("/today/updates", "today.updates.tsx"),
  route("/today/reviews-empty", "today.reviews-empty.tsx"),
  route("/navigation/history", "navigation.history.tsx"),
  route("/navigation/start", "navigation.start.tsx"),
  route("/pulse", "pulse.tsx"),
  route("/reminders", "reminders.tsx"),
  route("/settings", "settings.tsx"),
  route("/clients", "clients.tsx"),
  route("/clients/$clientId", "clients.$clientId.tsx"),
  route("/work", "work.tsx"),
  route("/work/$workId", "work.$workId.tsx"),
  route("/workflows", "workflows.tsx"),
  route("/workflows/$workflowId", "workflows.$workflowId.tsx"),
  route("/projects", "projects.tsx"),
  route("/projects/$projectId", "projects.$projectId.tsx"),
  route("/factory", "factory.tsx"),
  route("/factory/projects", "factory.projects.tsx"),
  route("/factory/plans", "factory.plans.tsx"),
  route("/factory/plan/$planId", "factory.plan.$planId.tsx"),
  route("/factory/project/$projectId", "factory.project.$projectId.tsx"),
  route("/factory/review/$runId", "factory.review.$runId.tsx"),
  route("/factory/sessions", "factory.sessions.tsx"),
  route("/factory/states", "factory.states.tsx"),
  route("/messages/new", "messages.new.tsx"),
  route("/channels/pins/$channelId", "channels.pins.$channelId.tsx"),
  route("/channels/$channelId", "channels.$channelId.tsx"),
  route(
    "/channels/$channelId/posts/$postId",
    "channels.$channelId.posts.$postId.tsx",
  ),
]);
