// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as workflowsRouteImport } from "./routes/workflows";
import { Route as workRouteImport } from "./routes/work";
import { Route as todayRouteImport } from "./routes/today";
import { Route as supervisionRouteImport } from "./routes/supervision";
import { Route as settingsRouteImport } from "./routes/settings";
import { Route as remindersRouteImport } from "./routes/reminders";
import { Route as pulseRouteImport } from "./routes/pulse";
import { Route as projectsRouteImport } from "./routes/projects";
import { Route as powerRouteImport } from "./routes/power";
import { Route as pipelineRouteImport } from "./routes/pipeline";
import { Route as leadsRouteImport } from "./routes/leads";
import { Route as goalsRouteImport } from "./routes/goals";
import { Route as factoryRouteImport } from "./routes/factory";
import { Route as discoveryRouteImport } from "./routes/discovery";
import { Route as companyWorkRouteImport } from "./routes/company-work";
import { Route as clientsRouteImport } from "./routes/clients";
import { Route as campaignRouteImport } from "./routes/campaign";
import { Route as agentsRouteImport } from "./routes/agents";
import { Route as indexRouteImport } from "./routes/index";
import { Route as workflowsDotworkflowIdRouteImport } from "./routes/workflows.$workflowId";
import { Route as workDotnewRouteImport } from "./routes/work.new";
import { Route as workDotworkIdRouteImport } from "./routes/work.$workId";
import { Route as todayDotupdatesRouteImport } from "./routes/today.updates";
import { Route as todayDotreviewsEmptyRouteImport } from "./routes/today.reviews-empty";
import { Route as salesDotserviceRouteImport } from "./routes/sales.service";
import { Route as salesDotproposalsRouteImport } from "./routes/sales.proposals";
import { Route as projectsDotprojectIdRouteImport } from "./routes/projects.$projectId";
import { Route as navigationDotstartRouteImport } from "./routes/navigation.start";
import { Route as navigationDothistoryRouteImport } from "./routes/navigation.history";
import { Route as messagesDotnewRouteImport } from "./routes/messages.new";
import { Route as goalsDotreferenceRouteImport } from "./routes/goals.reference";
import { Route as goalsDotnewRouteImport } from "./routes/goals.new";
import { Route as goalsDotgoalIdRouteImport } from "./routes/goals.$goalId";
import { Route as factoryDotstatesRouteImport } from "./routes/factory.states";
import { Route as factoryDotsessionsRouteImport } from "./routes/factory.sessions";
import { Route as factoryDotprojectsRouteImport } from "./routes/factory.projects";
import { Route as factoryDotplansRouteImport } from "./routes/factory.plans";
import { Route as clientsDotclientIdRouteImport } from "./routes/clients.$clientId";
import { Route as channelsDotchannelIdRouteImport } from "./routes/channels.$channelId";
import { Route as workDotverifyDotworkItemIdRouteImport } from "./routes/work.verify.$workItemId";
import { Route as workDotstatusDotworkItemIdRouteImport } from "./routes/work.status.$workItemId";
import { Route as workDotfromChatDotmessageIdRouteImport } from "./routes/work.from-chat.$messageId";
import { Route as workDoteditDotworkItemIdRouteImport } from "./routes/work.edit.$workItemId";
import { Route as workDotdetailDotworkItemIdRouteImport } from "./routes/work.detail.$workItemId";
import { Route as workDotarchiveDotworkItemIdRouteImport } from "./routes/work.archive.$workItemId";
import { Route as salesDotproposalDotproposalFormRouteImport } from "./routes/sales.proposal.proposal-form";
import { Route as salesDotproposalDotproposalIdRouteImport } from "./routes/sales.proposal.$proposalId";
import { Route as salesDotleadDotformFieldRouteImport } from "./routes/sales.lead.form-field";
import { Route as salesDotleadDotprospectIdRouteImport } from "./routes/sales.lead.$prospectId";
import { Route as goalsDotlinkDotgoalIdRouteImport } from "./routes/goals.link.$goalId";
import { Route as goalsDotgoalIdDotsubgoalRouteImport } from "./routes/goals.$goalId.subgoal";
import { Route as goalsDotgoalIdDotshareRouteImport } from "./routes/goals.$goalId.share";
import { Route as goalsDotgoalIdDotprogressRouteImport } from "./routes/goals.$goalId.progress";
import { Route as goalsDotgoalIdDoteditRouteImport } from "./routes/goals.$goalId.edit";
import { Route as goalsDotgoalIdDotdeleteRouteImport } from "./routes/goals.$goalId.delete";
import { Route as goalsDotgoalIdDotarchiveRouteImport } from "./routes/goals.$goalId.archive";
import { Route as factoryDotreviewDotrunIdRouteImport } from "./routes/factory.review.$runId";
import { Route as factoryDotprojectDotprojectIdRouteImport } from "./routes/factory.project.$projectId";
import { Route as factoryDotplanDotplanIdRouteImport } from "./routes/factory.plan.$planId";
import { Route as channelsDotpinsDotchannelIdRouteImport } from "./routes/channels.pins.$channelId";
import { Route as asksDotchannelIdDotaskIdRouteImport } from "./routes/asks.$channelId.$askId";
import { Route as channelsDotchannelIdDotpostsDotpostIdRouteImport } from "./routes/channels.$channelId.posts.$postId";

const workflowsRoute = workflowsRouteImport.update({
  id: "/workflows",
  path: "/workflows",
  getParentRoute: () => rootRouteImport,
} as any);
const workRoute = workRouteImport.update({
  id: "/work",
  path: "/work",
  getParentRoute: () => rootRouteImport,
} as any);
const todayRoute = todayRouteImport.update({
  id: "/today",
  path: "/today",
  getParentRoute: () => rootRouteImport,
} as any);
const supervisionRoute = supervisionRouteImport.update({
  id: "/supervision",
  path: "/supervision",
  getParentRoute: () => rootRouteImport,
} as any);
const settingsRoute = settingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const remindersRoute = remindersRouteImport.update({
  id: "/reminders",
  path: "/reminders",
  getParentRoute: () => rootRouteImport,
} as any);
const pulseRoute = pulseRouteImport.update({
  id: "/pulse",
  path: "/pulse",
  getParentRoute: () => rootRouteImport,
} as any);
const projectsRoute = projectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any);
const powerRoute = powerRouteImport.update({
  id: "/power",
  path: "/power",
  getParentRoute: () => rootRouteImport,
} as any);
const pipelineRoute = pipelineRouteImport.update({
  id: "/pipeline",
  path: "/pipeline",
  getParentRoute: () => rootRouteImport,
} as any);
const leadsRoute = leadsRouteImport.update({
  id: "/leads",
  path: "/leads",
  getParentRoute: () => rootRouteImport,
} as any);
const goalsRoute = goalsRouteImport.update({
  id: "/goals",
  path: "/goals",
  getParentRoute: () => rootRouteImport,
} as any);
const factoryRoute = factoryRouteImport.update({
  id: "/factory",
  path: "/factory",
  getParentRoute: () => rootRouteImport,
} as any);
const discoveryRoute = discoveryRouteImport.update({
  id: "/discovery",
  path: "/discovery",
  getParentRoute: () => rootRouteImport,
} as any);
const companyWorkRoute = companyWorkRouteImport.update({
  id: "/company-work",
  path: "/company-work",
  getParentRoute: () => rootRouteImport,
} as any);
const clientsRoute = clientsRouteImport.update({
  id: "/clients",
  path: "/clients",
  getParentRoute: () => rootRouteImport,
} as any);
const campaignRoute = campaignRouteImport.update({
  id: "/campaign",
  path: "/campaign",
  getParentRoute: () => rootRouteImport,
} as any);
const agentsRoute = agentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const workflowsDotworkflowIdRoute = workflowsDotworkflowIdRouteImport.update({
  id: "/workflows/$workflowId",
  path: "/workflows/$workflowId",
  getParentRoute: () => rootRouteImport,
} as any);
const workDotnewRoute = workDotnewRouteImport.update({
  id: "/work/new",
  path: "/work/new",
  getParentRoute: () => rootRouteImport,
} as any);
const workDotworkIdRoute = workDotworkIdRouteImport.update({
  id: "/work/$workId",
  path: "/work/$workId",
  getParentRoute: () => rootRouteImport,
} as any);
const todayDotupdatesRoute = todayDotupdatesRouteImport.update({
  id: "/today/updates",
  path: "/today/updates",
  getParentRoute: () => rootRouteImport,
} as any);
const todayDotreviewsEmptyRoute = todayDotreviewsEmptyRouteImport.update({
  id: "/today/reviews-empty",
  path: "/today/reviews-empty",
  getParentRoute: () => rootRouteImport,
} as any);
const salesDotserviceRoute = salesDotserviceRouteImport.update({
  id: "/sales/service",
  path: "/sales/service",
  getParentRoute: () => rootRouteImport,
} as any);
const salesDotproposalsRoute = salesDotproposalsRouteImport.update({
  id: "/sales/proposals",
  path: "/sales/proposals",
  getParentRoute: () => rootRouteImport,
} as any);
const projectsDotprojectIdRoute = projectsDotprojectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => rootRouteImport,
} as any);
const navigationDotstartRoute = navigationDotstartRouteImport.update({
  id: "/navigation/start",
  path: "/navigation/start",
  getParentRoute: () => rootRouteImport,
} as any);
const navigationDothistoryRoute = navigationDothistoryRouteImport.update({
  id: "/navigation/history",
  path: "/navigation/history",
  getParentRoute: () => rootRouteImport,
} as any);
const messagesDotnewRoute = messagesDotnewRouteImport.update({
  id: "/messages/new",
  path: "/messages/new",
  getParentRoute: () => rootRouteImport,
} as any);
const goalsDotreferenceRoute = goalsDotreferenceRouteImport.update({
  id: "/goals/reference",
  path: "/goals/reference",
  getParentRoute: () => rootRouteImport,
} as any);
const goalsDotnewRoute = goalsDotnewRouteImport.update({
  id: "/goals/new",
  path: "/goals/new",
  getParentRoute: () => rootRouteImport,
} as any);
const goalsDotgoalIdRoute = goalsDotgoalIdRouteImport.update({
  id: "/goals/$goalId",
  path: "/goals/$goalId",
  getParentRoute: () => rootRouteImport,
} as any);
const factoryDotstatesRoute = factoryDotstatesRouteImport.update({
  id: "/factory/states",
  path: "/factory/states",
  getParentRoute: () => rootRouteImport,
} as any);
const factoryDotsessionsRoute = factoryDotsessionsRouteImport.update({
  id: "/factory/sessions",
  path: "/factory/sessions",
  getParentRoute: () => rootRouteImport,
} as any);
const factoryDotprojectsRoute = factoryDotprojectsRouteImport.update({
  id: "/factory/projects",
  path: "/factory/projects",
  getParentRoute: () => rootRouteImport,
} as any);
const factoryDotplansRoute = factoryDotplansRouteImport.update({
  id: "/factory/plans",
  path: "/factory/plans",
  getParentRoute: () => rootRouteImport,
} as any);
const clientsDotclientIdRoute = clientsDotclientIdRouteImport.update({
  id: "/clients/$clientId",
  path: "/clients/$clientId",
  getParentRoute: () => rootRouteImport,
} as any);
const channelsDotchannelIdRoute = channelsDotchannelIdRouteImport.update({
  id: "/channels/$channelId",
  path: "/channels/$channelId",
  getParentRoute: () => rootRouteImport,
} as any);
const workDotverifyDotworkItemIdRoute =
  workDotverifyDotworkItemIdRouteImport.update({
    id: "/work/verify/$workItemId",
    path: "/work/verify/$workItemId",
    getParentRoute: () => rootRouteImport,
  } as any);
const workDotstatusDotworkItemIdRoute =
  workDotstatusDotworkItemIdRouteImport.update({
    id: "/work/status/$workItemId",
    path: "/work/status/$workItemId",
    getParentRoute: () => rootRouteImport,
  } as any);
const workDotfromChatDotmessageIdRoute =
  workDotfromChatDotmessageIdRouteImport.update({
    id: "/work/from-chat/$messageId",
    path: "/work/from-chat/$messageId",
    getParentRoute: () => rootRouteImport,
  } as any);
const workDoteditDotworkItemIdRoute =
  workDoteditDotworkItemIdRouteImport.update({
    id: "/work/edit/$workItemId",
    path: "/work/edit/$workItemId",
    getParentRoute: () => rootRouteImport,
  } as any);
const workDotdetailDotworkItemIdRoute =
  workDotdetailDotworkItemIdRouteImport.update({
    id: "/work/detail/$workItemId",
    path: "/work/detail/$workItemId",
    getParentRoute: () => rootRouteImport,
  } as any);
const workDotarchiveDotworkItemIdRoute =
  workDotarchiveDotworkItemIdRouteImport.update({
    id: "/work/archive/$workItemId",
    path: "/work/archive/$workItemId",
    getParentRoute: () => rootRouteImport,
  } as any);
const salesDotproposalDotproposalFormRoute =
  salesDotproposalDotproposalFormRouteImport.update({
    id: "/sales/proposal/proposal-form",
    path: "/sales/proposal/proposal-form",
    getParentRoute: () => rootRouteImport,
  } as any);
const salesDotproposalDotproposalIdRoute =
  salesDotproposalDotproposalIdRouteImport.update({
    id: "/sales/proposal/$proposalId",
    path: "/sales/proposal/$proposalId",
    getParentRoute: () => rootRouteImport,
  } as any);
const salesDotleadDotformFieldRoute =
  salesDotleadDotformFieldRouteImport.update({
    id: "/sales/lead/form-field",
    path: "/sales/lead/form-field",
    getParentRoute: () => rootRouteImport,
  } as any);
const salesDotleadDotprospectIdRoute =
  salesDotleadDotprospectIdRouteImport.update({
    id: "/sales/lead/$prospectId",
    path: "/sales/lead/$prospectId",
    getParentRoute: () => rootRouteImport,
  } as any);
const goalsDotlinkDotgoalIdRoute = goalsDotlinkDotgoalIdRouteImport.update({
  id: "/goals/link/$goalId",
  path: "/goals/link/$goalId",
  getParentRoute: () => rootRouteImport,
} as any);
const goalsDotgoalIdDotsubgoalRoute =
  goalsDotgoalIdDotsubgoalRouteImport.update({
    id: "/goals/$goalId/subgoal",
    path: "/goals/$goalId/subgoal",
    getParentRoute: () => rootRouteImport,
  } as any);
const goalsDotgoalIdDotshareRoute = goalsDotgoalIdDotshareRouteImport.update({
  id: "/goals/$goalId/share",
  path: "/goals/$goalId/share",
  getParentRoute: () => rootRouteImport,
} as any);
const goalsDotgoalIdDotprogressRoute =
  goalsDotgoalIdDotprogressRouteImport.update({
    id: "/goals/$goalId/progress",
    path: "/goals/$goalId/progress",
    getParentRoute: () => rootRouteImport,
  } as any);
const goalsDotgoalIdDoteditRoute = goalsDotgoalIdDoteditRouteImport.update({
  id: "/goals/$goalId/edit",
  path: "/goals/$goalId/edit",
  getParentRoute: () => rootRouteImport,
} as any);
const goalsDotgoalIdDotdeleteRoute = goalsDotgoalIdDotdeleteRouteImport.update({
  id: "/goals/$goalId/delete",
  path: "/goals/$goalId/delete",
  getParentRoute: () => rootRouteImport,
} as any);
const goalsDotgoalIdDotarchiveRoute =
  goalsDotgoalIdDotarchiveRouteImport.update({
    id: "/goals/$goalId/archive",
    path: "/goals/$goalId/archive",
    getParentRoute: () => rootRouteImport,
  } as any);
const factoryDotreviewDotrunIdRoute =
  factoryDotreviewDotrunIdRouteImport.update({
    id: "/factory/review/$runId",
    path: "/factory/review/$runId",
    getParentRoute: () => rootRouteImport,
  } as any);
const factoryDotprojectDotprojectIdRoute =
  factoryDotprojectDotprojectIdRouteImport.update({
    id: "/factory/project/$projectId",
    path: "/factory/project/$projectId",
    getParentRoute: () => rootRouteImport,
  } as any);
const factoryDotplanDotplanIdRoute = factoryDotplanDotplanIdRouteImport.update({
  id: "/factory/plan/$planId",
  path: "/factory/plan/$planId",
  getParentRoute: () => rootRouteImport,
} as any);
const channelsDotpinsDotchannelIdRoute =
  channelsDotpinsDotchannelIdRouteImport.update({
    id: "/channels/pins/$channelId",
    path: "/channels/pins/$channelId",
    getParentRoute: () => rootRouteImport,
  } as any);
const asksDotchannelIdDotaskIdRoute =
  asksDotchannelIdDotaskIdRouteImport.update({
    id: "/asks/$channelId/$askId",
    path: "/asks/$channelId/$askId",
    getParentRoute: () => rootRouteImport,
  } as any);
const channelsDotchannelIdDotpostsDotpostIdRoute =
  channelsDotchannelIdDotpostsDotpostIdRouteImport.update({
    id: "/channels/$channelId/posts/$postId",
    path: "/channels/$channelId/posts/$postId",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/campaign": typeof campaignRoute;
  "/clients": typeof clientsRoute;
  "/company-work": typeof companyWorkRoute;
  "/discovery": typeof discoveryRoute;
  "/factory": typeof factoryRoute;
  "/goals": typeof goalsRoute;
  "/leads": typeof leadsRoute;
  "/pipeline": typeof pipelineRoute;
  "/power": typeof powerRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/supervision": typeof supervisionRoute;
  "/today": typeof todayRoute;
  "/work": typeof workRoute;
  "/workflows": typeof workflowsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/clients/$clientId": typeof clientsDotclientIdRoute;
  "/factory/plans": typeof factoryDotplansRoute;
  "/factory/projects": typeof factoryDotprojectsRoute;
  "/factory/sessions": typeof factoryDotsessionsRoute;
  "/factory/states": typeof factoryDotstatesRoute;
  "/goals/$goalId": typeof goalsDotgoalIdRoute;
  "/goals/new": typeof goalsDotnewRoute;
  "/goals/reference": typeof goalsDotreferenceRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/navigation/history": typeof navigationDothistoryRoute;
  "/navigation/start": typeof navigationDotstartRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/sales/proposals": typeof salesDotproposalsRoute;
  "/sales/service": typeof salesDotserviceRoute;
  "/today/reviews-empty": typeof todayDotreviewsEmptyRoute;
  "/today/updates": typeof todayDotupdatesRoute;
  "/work/$workId": typeof workDotworkIdRoute;
  "/work/new": typeof workDotnewRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/asks/$channelId/$askId": typeof asksDotchannelIdDotaskIdRoute;
  "/channels/pins/$channelId": typeof channelsDotpinsDotchannelIdRoute;
  "/factory/plan/$planId": typeof factoryDotplanDotplanIdRoute;
  "/factory/project/$projectId": typeof factoryDotprojectDotprojectIdRoute;
  "/factory/review/$runId": typeof factoryDotreviewDotrunIdRoute;
  "/goals/$goalId/archive": typeof goalsDotgoalIdDotarchiveRoute;
  "/goals/$goalId/delete": typeof goalsDotgoalIdDotdeleteRoute;
  "/goals/$goalId/edit": typeof goalsDotgoalIdDoteditRoute;
  "/goals/$goalId/progress": typeof goalsDotgoalIdDotprogressRoute;
  "/goals/$goalId/share": typeof goalsDotgoalIdDotshareRoute;
  "/goals/$goalId/subgoal": typeof goalsDotgoalIdDotsubgoalRoute;
  "/goals/link/$goalId": typeof goalsDotlinkDotgoalIdRoute;
  "/sales/lead/$prospectId": typeof salesDotleadDotprospectIdRoute;
  "/sales/lead/form-field": typeof salesDotleadDotformFieldRoute;
  "/sales/proposal/$proposalId": typeof salesDotproposalDotproposalIdRoute;
  "/sales/proposal/proposal-form": typeof salesDotproposalDotproposalFormRoute;
  "/work/archive/$workItemId": typeof workDotarchiveDotworkItemIdRoute;
  "/work/detail/$workItemId": typeof workDotdetailDotworkItemIdRoute;
  "/work/edit/$workItemId": typeof workDoteditDotworkItemIdRoute;
  "/work/from-chat/$messageId": typeof workDotfromChatDotmessageIdRoute;
  "/work/status/$workItemId": typeof workDotstatusDotworkItemIdRoute;
  "/work/verify/$workItemId": typeof workDotverifyDotworkItemIdRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/campaign": typeof campaignRoute;
  "/clients": typeof clientsRoute;
  "/company-work": typeof companyWorkRoute;
  "/discovery": typeof discoveryRoute;
  "/factory": typeof factoryRoute;
  "/goals": typeof goalsRoute;
  "/leads": typeof leadsRoute;
  "/pipeline": typeof pipelineRoute;
  "/power": typeof powerRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/supervision": typeof supervisionRoute;
  "/today": typeof todayRoute;
  "/work": typeof workRoute;
  "/workflows": typeof workflowsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/clients/$clientId": typeof clientsDotclientIdRoute;
  "/factory/plans": typeof factoryDotplansRoute;
  "/factory/projects": typeof factoryDotprojectsRoute;
  "/factory/sessions": typeof factoryDotsessionsRoute;
  "/factory/states": typeof factoryDotstatesRoute;
  "/goals/$goalId": typeof goalsDotgoalIdRoute;
  "/goals/new": typeof goalsDotnewRoute;
  "/goals/reference": typeof goalsDotreferenceRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/navigation/history": typeof navigationDothistoryRoute;
  "/navigation/start": typeof navigationDotstartRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/sales/proposals": typeof salesDotproposalsRoute;
  "/sales/service": typeof salesDotserviceRoute;
  "/today/reviews-empty": typeof todayDotreviewsEmptyRoute;
  "/today/updates": typeof todayDotupdatesRoute;
  "/work/$workId": typeof workDotworkIdRoute;
  "/work/new": typeof workDotnewRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/asks/$channelId/$askId": typeof asksDotchannelIdDotaskIdRoute;
  "/channels/pins/$channelId": typeof channelsDotpinsDotchannelIdRoute;
  "/factory/plan/$planId": typeof factoryDotplanDotplanIdRoute;
  "/factory/project/$projectId": typeof factoryDotprojectDotprojectIdRoute;
  "/factory/review/$runId": typeof factoryDotreviewDotrunIdRoute;
  "/goals/$goalId/archive": typeof goalsDotgoalIdDotarchiveRoute;
  "/goals/$goalId/delete": typeof goalsDotgoalIdDotdeleteRoute;
  "/goals/$goalId/edit": typeof goalsDotgoalIdDoteditRoute;
  "/goals/$goalId/progress": typeof goalsDotgoalIdDotprogressRoute;
  "/goals/$goalId/share": typeof goalsDotgoalIdDotshareRoute;
  "/goals/$goalId/subgoal": typeof goalsDotgoalIdDotsubgoalRoute;
  "/goals/link/$goalId": typeof goalsDotlinkDotgoalIdRoute;
  "/sales/lead/$prospectId": typeof salesDotleadDotprospectIdRoute;
  "/sales/lead/form-field": typeof salesDotleadDotformFieldRoute;
  "/sales/proposal/$proposalId": typeof salesDotproposalDotproposalIdRoute;
  "/sales/proposal/proposal-form": typeof salesDotproposalDotproposalFormRoute;
  "/work/archive/$workItemId": typeof workDotarchiveDotworkItemIdRoute;
  "/work/detail/$workItemId": typeof workDotdetailDotworkItemIdRoute;
  "/work/edit/$workItemId": typeof workDoteditDotworkItemIdRoute;
  "/work/from-chat/$messageId": typeof workDotfromChatDotmessageIdRoute;
  "/work/status/$workItemId": typeof workDotstatusDotworkItemIdRoute;
  "/work/verify/$workItemId": typeof workDotverifyDotworkItemIdRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/campaign": typeof campaignRoute;
  "/clients": typeof clientsRoute;
  "/company-work": typeof companyWorkRoute;
  "/discovery": typeof discoveryRoute;
  "/factory": typeof factoryRoute;
  "/goals": typeof goalsRoute;
  "/leads": typeof leadsRoute;
  "/pipeline": typeof pipelineRoute;
  "/power": typeof powerRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/supervision": typeof supervisionRoute;
  "/today": typeof todayRoute;
  "/work": typeof workRoute;
  "/workflows": typeof workflowsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/clients/$clientId": typeof clientsDotclientIdRoute;
  "/factory/plans": typeof factoryDotplansRoute;
  "/factory/projects": typeof factoryDotprojectsRoute;
  "/factory/sessions": typeof factoryDotsessionsRoute;
  "/factory/states": typeof factoryDotstatesRoute;
  "/goals/$goalId": typeof goalsDotgoalIdRoute;
  "/goals/new": typeof goalsDotnewRoute;
  "/goals/reference": typeof goalsDotreferenceRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/navigation/history": typeof navigationDothistoryRoute;
  "/navigation/start": typeof navigationDotstartRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/sales/proposals": typeof salesDotproposalsRoute;
  "/sales/service": typeof salesDotserviceRoute;
  "/today/reviews-empty": typeof todayDotreviewsEmptyRoute;
  "/today/updates": typeof todayDotupdatesRoute;
  "/work/$workId": typeof workDotworkIdRoute;
  "/work/new": typeof workDotnewRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/asks/$channelId/$askId": typeof asksDotchannelIdDotaskIdRoute;
  "/channels/pins/$channelId": typeof channelsDotpinsDotchannelIdRoute;
  "/factory/plan/$planId": typeof factoryDotplanDotplanIdRoute;
  "/factory/project/$projectId": typeof factoryDotprojectDotprojectIdRoute;
  "/factory/review/$runId": typeof factoryDotreviewDotrunIdRoute;
  "/goals/$goalId/archive": typeof goalsDotgoalIdDotarchiveRoute;
  "/goals/$goalId/delete": typeof goalsDotgoalIdDotdeleteRoute;
  "/goals/$goalId/edit": typeof goalsDotgoalIdDoteditRoute;
  "/goals/$goalId/progress": typeof goalsDotgoalIdDotprogressRoute;
  "/goals/$goalId/share": typeof goalsDotgoalIdDotshareRoute;
  "/goals/$goalId/subgoal": typeof goalsDotgoalIdDotsubgoalRoute;
  "/goals/link/$goalId": typeof goalsDotlinkDotgoalIdRoute;
  "/sales/lead/$prospectId": typeof salesDotleadDotprospectIdRoute;
  "/sales/lead/form-field": typeof salesDotleadDotformFieldRoute;
  "/sales/proposal/$proposalId": typeof salesDotproposalDotproposalIdRoute;
  "/sales/proposal/proposal-form": typeof salesDotproposalDotproposalFormRoute;
  "/work/archive/$workItemId": typeof workDotarchiveDotworkItemIdRoute;
  "/work/detail/$workItemId": typeof workDotdetailDotworkItemIdRoute;
  "/work/edit/$workItemId": typeof workDoteditDotworkItemIdRoute;
  "/work/from-chat/$messageId": typeof workDotfromChatDotmessageIdRoute;
  "/work/status/$workItemId": typeof workDotstatusDotworkItemIdRoute;
  "/work/verify/$workItemId": typeof workDotverifyDotworkItemIdRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/agents"
    | "/campaign"
    | "/clients"
    | "/company-work"
    | "/discovery"
    | "/factory"
    | "/goals"
    | "/leads"
    | "/pipeline"
    | "/power"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/supervision"
    | "/today"
    | "/work"
    | "/workflows"
    | "/channels/$channelId"
    | "/clients/$clientId"
    | "/factory/plans"
    | "/factory/projects"
    | "/factory/sessions"
    | "/factory/states"
    | "/goals/$goalId"
    | "/goals/new"
    | "/goals/reference"
    | "/messages/new"
    | "/navigation/history"
    | "/navigation/start"
    | "/projects/$projectId"
    | "/sales/proposals"
    | "/sales/service"
    | "/today/reviews-empty"
    | "/today/updates"
    | "/work/$workId"
    | "/work/new"
    | "/workflows/$workflowId"
    | "/asks/$channelId/$askId"
    | "/channels/pins/$channelId"
    | "/factory/plan/$planId"
    | "/factory/project/$projectId"
    | "/factory/review/$runId"
    | "/goals/$goalId/archive"
    | "/goals/$goalId/delete"
    | "/goals/$goalId/edit"
    | "/goals/$goalId/progress"
    | "/goals/$goalId/share"
    | "/goals/$goalId/subgoal"
    | "/goals/link/$goalId"
    | "/sales/lead/$prospectId"
    | "/sales/lead/form-field"
    | "/sales/proposal/$proposalId"
    | "/sales/proposal/proposal-form"
    | "/work/archive/$workItemId"
    | "/work/detail/$workItemId"
    | "/work/edit/$workItemId"
    | "/work/from-chat/$messageId"
    | "/work/status/$workItemId"
    | "/work/verify/$workItemId"
    | "/channels/$channelId/posts/$postId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/agents"
    | "/campaign"
    | "/clients"
    | "/company-work"
    | "/discovery"
    | "/factory"
    | "/goals"
    | "/leads"
    | "/pipeline"
    | "/power"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/supervision"
    | "/today"
    | "/work"
    | "/workflows"
    | "/channels/$channelId"
    | "/clients/$clientId"
    | "/factory/plans"
    | "/factory/projects"
    | "/factory/sessions"
    | "/factory/states"
    | "/goals/$goalId"
    | "/goals/new"
    | "/goals/reference"
    | "/messages/new"
    | "/navigation/history"
    | "/navigation/start"
    | "/projects/$projectId"
    | "/sales/proposals"
    | "/sales/service"
    | "/today/reviews-empty"
    | "/today/updates"
    | "/work/$workId"
    | "/work/new"
    | "/workflows/$workflowId"
    | "/asks/$channelId/$askId"
    | "/channels/pins/$channelId"
    | "/factory/plan/$planId"
    | "/factory/project/$projectId"
    | "/factory/review/$runId"
    | "/goals/$goalId/archive"
    | "/goals/$goalId/delete"
    | "/goals/$goalId/edit"
    | "/goals/$goalId/progress"
    | "/goals/$goalId/share"
    | "/goals/$goalId/subgoal"
    | "/goals/link/$goalId"
    | "/sales/lead/$prospectId"
    | "/sales/lead/form-field"
    | "/sales/proposal/$proposalId"
    | "/sales/proposal/proposal-form"
    | "/work/archive/$workItemId"
    | "/work/detail/$workItemId"
    | "/work/edit/$workItemId"
    | "/work/from-chat/$messageId"
    | "/work/status/$workItemId"
    | "/work/verify/$workItemId"
    | "/channels/$channelId/posts/$postId";
  id:
    | "__root__"
    | "/"
    | "/agents"
    | "/campaign"
    | "/clients"
    | "/company-work"
    | "/discovery"
    | "/factory"
    | "/goals"
    | "/leads"
    | "/pipeline"
    | "/power"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/supervision"
    | "/today"
    | "/work"
    | "/workflows"
    | "/channels/$channelId"
    | "/clients/$clientId"
    | "/factory/plans"
    | "/factory/projects"
    | "/factory/sessions"
    | "/factory/states"
    | "/goals/$goalId"
    | "/goals/new"
    | "/goals/reference"
    | "/messages/new"
    | "/navigation/history"
    | "/navigation/start"
    | "/projects/$projectId"
    | "/sales/proposals"
    | "/sales/service"
    | "/today/reviews-empty"
    | "/today/updates"
    | "/work/$workId"
    | "/work/new"
    | "/workflows/$workflowId"
    | "/asks/$channelId/$askId"
    | "/channels/pins/$channelId"
    | "/factory/plan/$planId"
    | "/factory/project/$projectId"
    | "/factory/review/$runId"
    | "/goals/$goalId/archive"
    | "/goals/$goalId/delete"
    | "/goals/$goalId/edit"
    | "/goals/$goalId/progress"
    | "/goals/$goalId/share"
    | "/goals/$goalId/subgoal"
    | "/goals/link/$goalId"
    | "/sales/lead/$prospectId"
    | "/sales/lead/form-field"
    | "/sales/proposal/$proposalId"
    | "/sales/proposal/proposal-form"
    | "/work/archive/$workItemId"
    | "/work/detail/$workItemId"
    | "/work/edit/$workItemId"
    | "/work/from-chat/$messageId"
    | "/work/status/$workItemId"
    | "/work/verify/$workItemId"
    | "/channels/$channelId/posts/$postId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  agentsRoute: typeof agentsRoute;
  campaignRoute: typeof campaignRoute;
  clientsRoute: typeof clientsRoute;
  companyWorkRoute: typeof companyWorkRoute;
  discoveryRoute: typeof discoveryRoute;
  factoryRoute: typeof factoryRoute;
  goalsRoute: typeof goalsRoute;
  leadsRoute: typeof leadsRoute;
  pipelineRoute: typeof pipelineRoute;
  powerRoute: typeof powerRoute;
  projectsRoute: typeof projectsRoute;
  pulseRoute: typeof pulseRoute;
  remindersRoute: typeof remindersRoute;
  settingsRoute: typeof settingsRoute;
  supervisionRoute: typeof supervisionRoute;
  todayRoute: typeof todayRoute;
  workRoute: typeof workRoute;
  workflowsRoute: typeof workflowsRoute;
  channelsDotchannelIdRoute: typeof channelsDotchannelIdRoute;
  clientsDotclientIdRoute: typeof clientsDotclientIdRoute;
  factoryDotplansRoute: typeof factoryDotplansRoute;
  factoryDotprojectsRoute: typeof factoryDotprojectsRoute;
  factoryDotsessionsRoute: typeof factoryDotsessionsRoute;
  factoryDotstatesRoute: typeof factoryDotstatesRoute;
  goalsDotgoalIdRoute: typeof goalsDotgoalIdRoute;
  goalsDotnewRoute: typeof goalsDotnewRoute;
  goalsDotreferenceRoute: typeof goalsDotreferenceRoute;
  messagesDotnewRoute: typeof messagesDotnewRoute;
  navigationDothistoryRoute: typeof navigationDothistoryRoute;
  navigationDotstartRoute: typeof navigationDotstartRoute;
  projectsDotprojectIdRoute: typeof projectsDotprojectIdRoute;
  salesDotproposalsRoute: typeof salesDotproposalsRoute;
  salesDotserviceRoute: typeof salesDotserviceRoute;
  todayDotreviewsEmptyRoute: typeof todayDotreviewsEmptyRoute;
  todayDotupdatesRoute: typeof todayDotupdatesRoute;
  workDotworkIdRoute: typeof workDotworkIdRoute;
  workDotnewRoute: typeof workDotnewRoute;
  workflowsDotworkflowIdRoute: typeof workflowsDotworkflowIdRoute;
  asksDotchannelIdDotaskIdRoute: typeof asksDotchannelIdDotaskIdRoute;
  channelsDotpinsDotchannelIdRoute: typeof channelsDotpinsDotchannelIdRoute;
  factoryDotplanDotplanIdRoute: typeof factoryDotplanDotplanIdRoute;
  factoryDotprojectDotprojectIdRoute: typeof factoryDotprojectDotprojectIdRoute;
  factoryDotreviewDotrunIdRoute: typeof factoryDotreviewDotrunIdRoute;
  goalsDotgoalIdDotarchiveRoute: typeof goalsDotgoalIdDotarchiveRoute;
  goalsDotgoalIdDotdeleteRoute: typeof goalsDotgoalIdDotdeleteRoute;
  goalsDotgoalIdDoteditRoute: typeof goalsDotgoalIdDoteditRoute;
  goalsDotgoalIdDotprogressRoute: typeof goalsDotgoalIdDotprogressRoute;
  goalsDotgoalIdDotshareRoute: typeof goalsDotgoalIdDotshareRoute;
  goalsDotgoalIdDotsubgoalRoute: typeof goalsDotgoalIdDotsubgoalRoute;
  goalsDotlinkDotgoalIdRoute: typeof goalsDotlinkDotgoalIdRoute;
  salesDotleadDotprospectIdRoute: typeof salesDotleadDotprospectIdRoute;
  salesDotleadDotformFieldRoute: typeof salesDotleadDotformFieldRoute;
  salesDotproposalDotproposalIdRoute: typeof salesDotproposalDotproposalIdRoute;
  salesDotproposalDotproposalFormRoute: typeof salesDotproposalDotproposalFormRoute;
  workDotarchiveDotworkItemIdRoute: typeof workDotarchiveDotworkItemIdRoute;
  workDotdetailDotworkItemIdRoute: typeof workDotdetailDotworkItemIdRoute;
  workDoteditDotworkItemIdRoute: typeof workDoteditDotworkItemIdRoute;
  workDotfromChatDotmessageIdRoute: typeof workDotfromChatDotmessageIdRoute;
  workDotstatusDotworkItemIdRoute: typeof workDotstatusDotworkItemIdRoute;
  workDotverifyDotworkItemIdRoute: typeof workDotverifyDotworkItemIdRoute;
  channelsDotchannelIdDotpostsDotpostIdRoute: typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/workflows": {
      id: "/workflows";
      path: "/workflows";
      fullPath: "/workflows";
      preLoaderRoute: typeof workflowsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/work": {
      id: "/work";
      path: "/work";
      fullPath: "/work";
      preLoaderRoute: typeof workRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/today": {
      id: "/today";
      path: "/today";
      fullPath: "/today";
      preLoaderRoute: typeof todayRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/supervision": {
      id: "/supervision";
      path: "/supervision";
      fullPath: "/supervision";
      preLoaderRoute: typeof supervisionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof settingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reminders": {
      id: "/reminders";
      path: "/reminders";
      fullPath: "/reminders";
      preLoaderRoute: typeof remindersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pulse": {
      id: "/pulse";
      path: "/pulse";
      fullPath: "/pulse";
      preLoaderRoute: typeof pulseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects": {
      id: "/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof projectsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/power": {
      id: "/power";
      path: "/power";
      fullPath: "/power";
      preLoaderRoute: typeof powerRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pipeline": {
      id: "/pipeline";
      path: "/pipeline";
      fullPath: "/pipeline";
      preLoaderRoute: typeof pipelineRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/leads": {
      id: "/leads";
      path: "/leads";
      fullPath: "/leads";
      preLoaderRoute: typeof leadsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/goals": {
      id: "/goals";
      path: "/goals";
      fullPath: "/goals";
      preLoaderRoute: typeof goalsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/factory": {
      id: "/factory";
      path: "/factory";
      fullPath: "/factory";
      preLoaderRoute: typeof factoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/discovery": {
      id: "/discovery";
      path: "/discovery";
      fullPath: "/discovery";
      preLoaderRoute: typeof discoveryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/company-work": {
      id: "/company-work";
      path: "/company-work";
      fullPath: "/company-work";
      preLoaderRoute: typeof companyWorkRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/clients": {
      id: "/clients";
      path: "/clients";
      fullPath: "/clients";
      preLoaderRoute: typeof clientsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/campaign": {
      id: "/campaign";
      path: "/campaign";
      fullPath: "/campaign";
      preLoaderRoute: typeof campaignRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agents": {
      id: "/agents";
      path: "/agents";
      fullPath: "/agents";
      preLoaderRoute: typeof agentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workflows/$workflowId": {
      id: "/workflows/$workflowId";
      path: "/workflows/$workflowId";
      fullPath: "/workflows/$workflowId";
      preLoaderRoute: typeof workflowsDotworkflowIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/work/new": {
      id: "/work/new";
      path: "/work/new";
      fullPath: "/work/new";
      preLoaderRoute: typeof workDotnewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/work/$workId": {
      id: "/work/$workId";
      path: "/work/$workId";
      fullPath: "/work/$workId";
      preLoaderRoute: typeof workDotworkIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/today/updates": {
      id: "/today/updates";
      path: "/today/updates";
      fullPath: "/today/updates";
      preLoaderRoute: typeof todayDotupdatesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/today/reviews-empty": {
      id: "/today/reviews-empty";
      path: "/today/reviews-empty";
      fullPath: "/today/reviews-empty";
      preLoaderRoute: typeof todayDotreviewsEmptyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sales/service": {
      id: "/sales/service";
      path: "/sales/service";
      fullPath: "/sales/service";
      preLoaderRoute: typeof salesDotserviceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sales/proposals": {
      id: "/sales/proposals";
      path: "/sales/proposals";
      fullPath: "/sales/proposals";
      preLoaderRoute: typeof salesDotproposalsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/$projectId": {
      id: "/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof projectsDotprojectIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/navigation/start": {
      id: "/navigation/start";
      path: "/navigation/start";
      fullPath: "/navigation/start";
      preLoaderRoute: typeof navigationDotstartRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/navigation/history": {
      id: "/navigation/history";
      path: "/navigation/history";
      fullPath: "/navigation/history";
      preLoaderRoute: typeof navigationDothistoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/messages/new": {
      id: "/messages/new";
      path: "/messages/new";
      fullPath: "/messages/new";
      preLoaderRoute: typeof messagesDotnewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/goals/reference": {
      id: "/goals/reference";
      path: "/goals/reference";
      fullPath: "/goals/reference";
      preLoaderRoute: typeof goalsDotreferenceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/goals/new": {
      id: "/goals/new";
      path: "/goals/new";
      fullPath: "/goals/new";
      preLoaderRoute: typeof goalsDotnewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/goals/$goalId": {
      id: "/goals/$goalId";
      path: "/goals/$goalId";
      fullPath: "/goals/$goalId";
      preLoaderRoute: typeof goalsDotgoalIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/factory/states": {
      id: "/factory/states";
      path: "/factory/states";
      fullPath: "/factory/states";
      preLoaderRoute: typeof factoryDotstatesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/factory/sessions": {
      id: "/factory/sessions";
      path: "/factory/sessions";
      fullPath: "/factory/sessions";
      preLoaderRoute: typeof factoryDotsessionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/factory/projects": {
      id: "/factory/projects";
      path: "/factory/projects";
      fullPath: "/factory/projects";
      preLoaderRoute: typeof factoryDotprojectsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/factory/plans": {
      id: "/factory/plans";
      path: "/factory/plans";
      fullPath: "/factory/plans";
      preLoaderRoute: typeof factoryDotplansRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/clients/$clientId": {
      id: "/clients/$clientId";
      path: "/clients/$clientId";
      fullPath: "/clients/$clientId";
      preLoaderRoute: typeof clientsDotclientIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels/$channelId": {
      id: "/channels/$channelId";
      path: "/channels/$channelId";
      fullPath: "/channels/$channelId";
      preLoaderRoute: typeof channelsDotchannelIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/work/verify/$workItemId": {
      id: "/work/verify/$workItemId";
      path: "/work/verify/$workItemId";
      fullPath: "/work/verify/$workItemId";
      preLoaderRoute: typeof workDotverifyDotworkItemIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/work/status/$workItemId": {
      id: "/work/status/$workItemId";
      path: "/work/status/$workItemId";
      fullPath: "/work/status/$workItemId";
      preLoaderRoute: typeof workDotstatusDotworkItemIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/work/from-chat/$messageId": {
      id: "/work/from-chat/$messageId";
      path: "/work/from-chat/$messageId";
      fullPath: "/work/from-chat/$messageId";
      preLoaderRoute: typeof workDotfromChatDotmessageIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/work/edit/$workItemId": {
      id: "/work/edit/$workItemId";
      path: "/work/edit/$workItemId";
      fullPath: "/work/edit/$workItemId";
      preLoaderRoute: typeof workDoteditDotworkItemIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/work/detail/$workItemId": {
      id: "/work/detail/$workItemId";
      path: "/work/detail/$workItemId";
      fullPath: "/work/detail/$workItemId";
      preLoaderRoute: typeof workDotdetailDotworkItemIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/work/archive/$workItemId": {
      id: "/work/archive/$workItemId";
      path: "/work/archive/$workItemId";
      fullPath: "/work/archive/$workItemId";
      preLoaderRoute: typeof workDotarchiveDotworkItemIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sales/proposal/proposal-form": {
      id: "/sales/proposal/proposal-form";
      path: "/sales/proposal/proposal-form";
      fullPath: "/sales/proposal/proposal-form";
      preLoaderRoute: typeof salesDotproposalDotproposalFormRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sales/proposal/$proposalId": {
      id: "/sales/proposal/$proposalId";
      path: "/sales/proposal/$proposalId";
      fullPath: "/sales/proposal/$proposalId";
      preLoaderRoute: typeof salesDotproposalDotproposalIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sales/lead/form-field": {
      id: "/sales/lead/form-field";
      path: "/sales/lead/form-field";
      fullPath: "/sales/lead/form-field";
      preLoaderRoute: typeof salesDotleadDotformFieldRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sales/lead/$prospectId": {
      id: "/sales/lead/$prospectId";
      path: "/sales/lead/$prospectId";
      fullPath: "/sales/lead/$prospectId";
      preLoaderRoute: typeof salesDotleadDotprospectIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/goals/link/$goalId": {
      id: "/goals/link/$goalId";
      path: "/goals/link/$goalId";
      fullPath: "/goals/link/$goalId";
      preLoaderRoute: typeof goalsDotlinkDotgoalIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/goals/$goalId/subgoal": {
      id: "/goals/$goalId/subgoal";
      path: "/goals/$goalId/subgoal";
      fullPath: "/goals/$goalId/subgoal";
      preLoaderRoute: typeof goalsDotgoalIdDotsubgoalRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/goals/$goalId/share": {
      id: "/goals/$goalId/share";
      path: "/goals/$goalId/share";
      fullPath: "/goals/$goalId/share";
      preLoaderRoute: typeof goalsDotgoalIdDotshareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/goals/$goalId/progress": {
      id: "/goals/$goalId/progress";
      path: "/goals/$goalId/progress";
      fullPath: "/goals/$goalId/progress";
      preLoaderRoute: typeof goalsDotgoalIdDotprogressRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/goals/$goalId/edit": {
      id: "/goals/$goalId/edit";
      path: "/goals/$goalId/edit";
      fullPath: "/goals/$goalId/edit";
      preLoaderRoute: typeof goalsDotgoalIdDoteditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/goals/$goalId/delete": {
      id: "/goals/$goalId/delete";
      path: "/goals/$goalId/delete";
      fullPath: "/goals/$goalId/delete";
      preLoaderRoute: typeof goalsDotgoalIdDotdeleteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/goals/$goalId/archive": {
      id: "/goals/$goalId/archive";
      path: "/goals/$goalId/archive";
      fullPath: "/goals/$goalId/archive";
      preLoaderRoute: typeof goalsDotgoalIdDotarchiveRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/factory/review/$runId": {
      id: "/factory/review/$runId";
      path: "/factory/review/$runId";
      fullPath: "/factory/review/$runId";
      preLoaderRoute: typeof factoryDotreviewDotrunIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/factory/project/$projectId": {
      id: "/factory/project/$projectId";
      path: "/factory/project/$projectId";
      fullPath: "/factory/project/$projectId";
      preLoaderRoute: typeof factoryDotprojectDotprojectIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/factory/plan/$planId": {
      id: "/factory/plan/$planId";
      path: "/factory/plan/$planId";
      fullPath: "/factory/plan/$planId";
      preLoaderRoute: typeof factoryDotplanDotplanIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels/pins/$channelId": {
      id: "/channels/pins/$channelId";
      path: "/channels/pins/$channelId";
      fullPath: "/channels/pins/$channelId";
      preLoaderRoute: typeof channelsDotpinsDotchannelIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/asks/$channelId/$askId": {
      id: "/asks/$channelId/$askId";
      path: "/asks/$channelId/$askId";
      fullPath: "/asks/$channelId/$askId";
      preLoaderRoute: typeof asksDotchannelIdDotaskIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels/$channelId/posts/$postId": {
      id: "/channels/$channelId/posts/$postId";
      path: "/channels/$channelId/posts/$postId";
      fullPath: "/channels/$channelId/posts/$postId";
      preLoaderRoute: typeof channelsDotchannelIdDotpostsDotpostIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  agentsRoute: agentsRoute,
  campaignRoute: campaignRoute,
  clientsRoute: clientsRoute,
  companyWorkRoute: companyWorkRoute,
  discoveryRoute: discoveryRoute,
  factoryRoute: factoryRoute,
  goalsRoute: goalsRoute,
  leadsRoute: leadsRoute,
  pipelineRoute: pipelineRoute,
  powerRoute: powerRoute,
  projectsRoute: projectsRoute,
  pulseRoute: pulseRoute,
  remindersRoute: remindersRoute,
  settingsRoute: settingsRoute,
  supervisionRoute: supervisionRoute,
  todayRoute: todayRoute,
  workRoute: workRoute,
  workflowsRoute: workflowsRoute,
  channelsDotchannelIdRoute: channelsDotchannelIdRoute,
  clientsDotclientIdRoute: clientsDotclientIdRoute,
  factoryDotplansRoute: factoryDotplansRoute,
  factoryDotprojectsRoute: factoryDotprojectsRoute,
  factoryDotsessionsRoute: factoryDotsessionsRoute,
  factoryDotstatesRoute: factoryDotstatesRoute,
  goalsDotgoalIdRoute: goalsDotgoalIdRoute,
  goalsDotnewRoute: goalsDotnewRoute,
  goalsDotreferenceRoute: goalsDotreferenceRoute,
  messagesDotnewRoute: messagesDotnewRoute,
  navigationDothistoryRoute: navigationDothistoryRoute,
  navigationDotstartRoute: navigationDotstartRoute,
  projectsDotprojectIdRoute: projectsDotprojectIdRoute,
  salesDotproposalsRoute: salesDotproposalsRoute,
  salesDotserviceRoute: salesDotserviceRoute,
  todayDotreviewsEmptyRoute: todayDotreviewsEmptyRoute,
  todayDotupdatesRoute: todayDotupdatesRoute,
  workDotworkIdRoute: workDotworkIdRoute,
  workDotnewRoute: workDotnewRoute,
  workflowsDotworkflowIdRoute: workflowsDotworkflowIdRoute,
  asksDotchannelIdDotaskIdRoute: asksDotchannelIdDotaskIdRoute,
  channelsDotpinsDotchannelIdRoute: channelsDotpinsDotchannelIdRoute,
  factoryDotplanDotplanIdRoute: factoryDotplanDotplanIdRoute,
  factoryDotprojectDotprojectIdRoute: factoryDotprojectDotprojectIdRoute,
  factoryDotreviewDotrunIdRoute: factoryDotreviewDotrunIdRoute,
  goalsDotgoalIdDotarchiveRoute: goalsDotgoalIdDotarchiveRoute,
  goalsDotgoalIdDotdeleteRoute: goalsDotgoalIdDotdeleteRoute,
  goalsDotgoalIdDoteditRoute: goalsDotgoalIdDoteditRoute,
  goalsDotgoalIdDotprogressRoute: goalsDotgoalIdDotprogressRoute,
  goalsDotgoalIdDotshareRoute: goalsDotgoalIdDotshareRoute,
  goalsDotgoalIdDotsubgoalRoute: goalsDotgoalIdDotsubgoalRoute,
  goalsDotlinkDotgoalIdRoute: goalsDotlinkDotgoalIdRoute,
  salesDotleadDotprospectIdRoute: salesDotleadDotprospectIdRoute,
  salesDotleadDotformFieldRoute: salesDotleadDotformFieldRoute,
  salesDotproposalDotproposalIdRoute: salesDotproposalDotproposalIdRoute,
  salesDotproposalDotproposalFormRoute: salesDotproposalDotproposalFormRoute,
  workDotarchiveDotworkItemIdRoute: workDotarchiveDotworkItemIdRoute,
  workDotdetailDotworkItemIdRoute: workDotdetailDotworkItemIdRoute,
  workDoteditDotworkItemIdRoute: workDoteditDotworkItemIdRoute,
  workDotfromChatDotmessageIdRoute: workDotfromChatDotmessageIdRoute,
  workDotstatusDotworkItemIdRoute: workDotstatusDotworkItemIdRoute,
  workDotverifyDotworkItemIdRoute: workDotverifyDotworkItemIdRoute,
  channelsDotchannelIdDotpostsDotpostIdRoute:
    channelsDotchannelIdDotpostsDotpostIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
